---
title: "Project Data Science"
author: "Muhammad Khairul Rizal"
date: "12/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

import library yang diperlukan
```{r cars}
library(shiny)
library(tidymodels)
library(here)
library(vroom)
library(ggplot2)
library(dplyr)
library(shinythemes)
library(tidytext)
library(wordcloud2)
```
import file excel, lalu melakukan pembersihan terhadap kolom Review_Text
kemudian menggunakan sentiment lexicon bing untuk analisis sentiment
```{r cars}
review <- vroom(here("DisneylandReviews.csv"))

review_word <- review %>%
  filter(Review_Text != "nan") %>%
  unnest_tokens(word, Review_Text) %>%
  anti_join(stop_words) 

review <- review_word %>%
  inner_join(get_sentiments(lexicon = c("bing"))) 
```

```{r cars}
ui <- fluidPage(
    theme = shinytheme("slate"),
    # Application title
    titlePanel("Disneyland Reviews"),
    navbarPage("Sentiment Analysis",
        tabPanel
        ("Data",
          mainPanel
          ( 
            dataTableOutput("Table")
          )
        ),
        
        tabPanel
        ("Total Sentiment",
            mainPanel(
                plotOutput(outputId = "jumlah_sentiment")
            )
          ),
        
        tabPanel
        ("Word Sentiment",
            mainPanel(
                plotOutput(outputId = "word_sentiment")
            )
          ),
        
        tabPanel
        ("Reviewer Location",
            mainPanel(
                plotOutput(outputId = "location")
            )
          ),
        
        tabPanel
        ("Wordcloud",
            mainPanel(
                wordcloud2Output(outputId = "wordcloud")
            )
          )
        )
    
)
```

```{r cars}
server <- function(input, output,session) {
    
    output$Table <- renderDataTable(review)
    
    output$jumlah_sentiment <- renderPlot({
      review %>%
        count(sentiment)%>%
        ggplot(aes(reorder(sentiment,n), n,fill = sentiment)) +
        geom_col() +
        coord_flip() +
            labs(
             title = "Total Sentiment",
             x = "Sentiment",
             y = "Total"
            )+ theme(text = element_text(size=20),
                panel.background = element_rect(fill = "white")
                )
                
    })
    
    output$word_sentiment <- renderPlot({
      review %>%
        count(sentiment,word, sort=TRUE)%>%
        group_by(sentiment) %>%
        top_n(10) %>%
        ungroup() %>%
        mutate(word = reorder(word, n)) %>%
        ggplot(aes(word, n, fill = sentiment)) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~sentiment, scales = "free_y") +
        coord_flip()+
        labs(title = "Word Sentiment",
             y = "Total",
             x = "Word") +
        theme(text = element_text(size=20),
                panel.background = element_rect(fill = "white")
                )
    })
    
    output$location <- renderPlot({
      review %>%
        count(Reviewer_Location)%>%
        top_n(10) %>%
        ggplot(aes(reorder(Reviewer_Location,n), n,fill = Reviewer_Location)) +
        geom_col() +
        coord_flip() +
            labs(
             title = "Reviewer Location",
             x = "Location",
             y = "Total"
            )+ theme(text = element_text(size=20),
                panel.background = element_rect(fill = "white")
                )
                
    })
    
    output$wordcloud <- renderWordcloud2({
      data1 <- review%>%
        count(word,sort =TRUE)
     wordcloud2(data=data1, size=0.5,color='random-dark')
    })
}
```

```{r cars}
shinyApp(ui = ui, server = server)
```